/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadyScreenRouteImport } from './routes/ready-screen'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenNotificationsRouteImport } from './routes/kitchen-notifications'
import { Route as KitchenHistoryRouteImport } from './routes/kitchen-history'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminSlotsRouteImport } from './routes/admin-slots'
import { Route as AdminOrdersRouteImport } from './routes/admin-orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin-notifications'
import { Route as AdminMenuRouteImport } from './routes/admin-menu'
import { Route as AdminKitchenRouteImport } from './routes/admin-kitchen'
import { Route as AdminGuestOrdersRouteImport } from './routes/admin-guest-orders'
import { Route as AdminEmployeesRouteImport } from './routes/admin-employees'
import { Route as AdminCounterRouteImport } from './routes/admin-counter'
import { Route as AdminBillingRouteImport } from './routes/admin-billing'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin-announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSetPasswordRouteImport } from './routes/admin/set-password'
import { Route as AdminMenuCreateRouteImport } from './routes/admin/menu-create'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyScreenRoute = ReadyScreenRouteImport.update({
  id: '/ready-screen',
  path: '/ready-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenNotificationsRoute = KitchenNotificationsRouteImport.update({
  id: '/kitchen-notifications',
  path: '/kitchen-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenHistoryRoute = KitchenHistoryRouteImport.update({
  id: '/kitchen-history',
  path: '/kitchen-history',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlotsRoute = AdminSlotsRouteImport.update({
  id: '/admin-slots',
  path: '/admin-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin-orders',
  path: '/admin-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin-notifications',
  path: '/admin-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin-menu',
  path: '/admin-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/admin-kitchen',
  path: '/admin-kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuestOrdersRoute = AdminGuestOrdersRouteImport.update({
  id: '/admin-guest-orders',
  path: '/admin-guest-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin-employees',
  path: '/admin-employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCounterRoute = AdminCounterRouteImport.update({
  id: '/admin-counter',
  path: '/admin-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin-billing',
  path: '/admin-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin-announcements',
  path: '/admin-announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuCreateRoute = AdminMenuCreateRouteImport.update({
  id: '/menu-create',
  path: '/menu-create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-billing': typeof AdminBillingRoute
  '/admin-counter': typeof AdminCounterRoute
  '/admin-employees': typeof AdminEmployeesRoute
  '/admin-guest-orders': typeof AdminGuestOrdersRoute
  '/admin-kitchen': typeof AdminKitchenRoute
  '/admin-menu': typeof AdminMenuRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-slots': typeof AdminSlotsRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-history': typeof KitchenHistoryRoute
  '/kitchen-notifications': typeof KitchenNotificationsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/ready-screen': typeof ReadyScreenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/menu-create': typeof AdminMenuCreateRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-billing': typeof AdminBillingRoute
  '/admin-counter': typeof AdminCounterRoute
  '/admin-employees': typeof AdminEmployeesRoute
  '/admin-guest-orders': typeof AdminGuestOrdersRoute
  '/admin-kitchen': typeof AdminKitchenRoute
  '/admin-menu': typeof AdminMenuRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-slots': typeof AdminSlotsRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-history': typeof KitchenHistoryRoute
  '/kitchen-notifications': typeof KitchenNotificationsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/ready-screen': typeof ReadyScreenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/menu-create': typeof AdminMenuCreateRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-billing': typeof AdminBillingRoute
  '/admin-counter': typeof AdminCounterRoute
  '/admin-employees': typeof AdminEmployeesRoute
  '/admin-guest-orders': typeof AdminGuestOrdersRoute
  '/admin-kitchen': typeof AdminKitchenRoute
  '/admin-menu': typeof AdminMenuRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-slots': typeof AdminSlotsRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-history': typeof KitchenHistoryRoute
  '/kitchen-notifications': typeof KitchenNotificationsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/ready-screen': typeof ReadyScreenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/wallet': typeof WalletRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/menu-create': typeof AdminMenuCreateRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-announcements'
    | '/admin-billing'
    | '/admin-counter'
    | '/admin-employees'
    | '/admin-guest-orders'
    | '/admin-kitchen'
    | '/admin-menu'
    | '/admin-notifications'
    | '/admin-orders'
    | '/admin-slots'
    | '/cart'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen'
    | '/kitchen-history'
    | '/kitchen-notifications'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/ready-screen'
    | '/reset-password'
    | '/set-password'
    | '/verify-otp'
    | '/wallet'
    | '/admin/audit-logs'
    | '/admin/menu-create'
    | '/admin/set-password'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-announcements'
    | '/admin-billing'
    | '/admin-counter'
    | '/admin-employees'
    | '/admin-guest-orders'
    | '/admin-kitchen'
    | '/admin-menu'
    | '/admin-notifications'
    | '/admin-orders'
    | '/admin-slots'
    | '/cart'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen'
    | '/kitchen-history'
    | '/kitchen-notifications'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/ready-screen'
    | '/reset-password'
    | '/set-password'
    | '/verify-otp'
    | '/wallet'
    | '/admin/audit-logs'
    | '/admin/menu-create'
    | '/admin/set-password'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-announcements'
    | '/admin-billing'
    | '/admin-counter'
    | '/admin-employees'
    | '/admin-guest-orders'
    | '/admin-kitchen'
    | '/admin-menu'
    | '/admin-notifications'
    | '/admin-orders'
    | '/admin-slots'
    | '/cart'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen'
    | '/kitchen-history'
    | '/kitchen-notifications'
    | '/login'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/ready-screen'
    | '/reset-password'
    | '/set-password'
    | '/verify-otp'
    | '/wallet'
    | '/admin/audit-logs'
    | '/admin/menu-create'
    | '/admin/set-password'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCounterRoute: typeof AdminCounterRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminGuestOrdersRoute: typeof AdminGuestOrdersRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSlotsRoute: typeof AdminSlotsRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenRoute: typeof KitchenRoute
  KitchenHistoryRoute: typeof KitchenHistoryRoute
  KitchenNotificationsRoute: typeof KitchenNotificationsRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ReadyScreenRoute: typeof ReadyScreenRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready-screen': {
      id: '/ready-screen'
      path: '/ready-screen'
      fullPath: '/ready-screen'
      preLoaderRoute: typeof ReadyScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-notifications': {
      id: '/kitchen-notifications'
      path: '/kitchen-notifications'
      fullPath: '/kitchen-notifications'
      preLoaderRoute: typeof KitchenNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-history': {
      id: '/kitchen-history'
      path: '/kitchen-history'
      fullPath: '/kitchen-history'
      preLoaderRoute: typeof KitchenHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-slots': {
      id: '/admin-slots'
      path: '/admin-slots'
      fullPath: '/admin-slots'
      preLoaderRoute: typeof AdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-orders': {
      id: '/admin-orders'
      path: '/admin-orders'
      fullPath: '/admin-orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-notifications': {
      id: '/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin-notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-menu': {
      id: '/admin-menu'
      path: '/admin-menu'
      fullPath: '/admin-menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kitchen': {
      id: '/admin-kitchen'
      path: '/admin-kitchen'
      fullPath: '/admin-kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-guest-orders': {
      id: '/admin-guest-orders'
      path: '/admin-guest-orders'
      fullPath: '/admin-guest-orders'
      preLoaderRoute: typeof AdminGuestOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-employees': {
      id: '/admin-employees'
      path: '/admin-employees'
      fullPath: '/admin-employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-counter': {
      id: '/admin-counter'
      path: '/admin-counter'
      fullPath: '/admin-counter'
      preLoaderRoute: typeof AdminCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-billing': {
      id: '/admin-billing'
      path: '/admin-billing'
      fullPath: '/admin-billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-announcements': {
      id: '/admin-announcements'
      path: '/admin-announcements'
      fullPath: '/admin-announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-create': {
      id: '/admin/menu-create'
      path: '/menu-create'
      fullPath: '/admin/menu-create'
      preLoaderRoute: typeof AdminMenuCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminMenuCreateRoute: typeof AdminMenuCreateRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminMenuCreateRoute: AdminMenuCreateRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCounterRoute: AdminCounterRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminGuestOrdersRoute: AdminGuestOrdersRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSlotsRoute: AdminSlotsRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenRoute: KitchenRoute,
  KitchenHistoryRoute: KitchenHistoryRoute,
  KitchenNotificationsRoute: KitchenNotificationsRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ReadyScreenRoute: ReadyScreenRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
