# Generated by Django 5.2.13 on 2026-05-05 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenCounterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('canteen_id', models.UUIDField(db_index=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('COUNTER', 'Counter')], db_index=True, max_length=10)),
                ('pin_hash', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kitchen / Counter User',
                'verbose_name_plural': 'Kitchen / Counter Users',
                'db_table': 'cms_kitchen_counter_users',
                'indexes': [models.Index(fields=['username', 'is_active'], name='idx_kcu_username_active'), models.Index(fields=['canteen_id', 'role'], name='idx_kcu_canteen_role')],
            },
        ),
    ]
