# Generated by Django 5.2.13 on 2026-05-06 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address_floor', models.TextField(blank=True, default='')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('operating_hours_start', models.TimeField(blank=True, null=True)),
                ('operating_hours_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canteen_locations', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_locations', to='accounts.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canteen_locations', to='accounts.location')),
            ],
            options={
                'db_table': 'cms_canteen_locations',
                'ordering': ['name'],
            },
        ),
    ]
