# Generated by Django 5.2.14 on 2026-05-08 10:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_canteenlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Beverages', 'Beverages')], db_column='category', max_length=20)),
                ('slot', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], db_column='slot', max_length=20)),
                ('tag', models.CharField(blank=True, db_column='tag', max_length=50)),
                ('live', models.BooleanField(db_column='is_live', default=True)),
                ('days', models.JSONField(db_column='available_days', default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'cms_menu_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, db_column='order_number', max_length=50, null=True, unique=True)),
                ('guest_name', models.CharField(db_column='guest_name', max_length=200)),
                ('guest_email', models.CharField(blank=True, db_column='guest_email', default='', max_length=254)),
                ('phone', models.CharField(db_column='guest_mobile', max_length=20)),
                ('total', models.DecimalField(db_column='total_amount', decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_column='status', default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('estimated_time', models.TimeField(blank=True, db_column='estimated_time', null=True)),
                ('special_instructions', models.TextField(blank=True, db_column='special_instructions')),
                ('canteen', models.ForeignKey(blank=True, db_column='canteen_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_orders', to='cms.canteenlocation')),
            ],
            options={
                'db_table': 'cms_guest_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestOrderItem',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='item_name', max_length=200)),
                ('price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.PositiveIntegerField(db_column='quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_custom', models.BooleanField(db_column='is_custom', default=False)),
                ('description', models.TextField(blank=True, db_column='item_description', default='')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.guestorder')),
            ],
            options={
                'db_table': 'cms_guest_order_items',
            },
        ),
    ]
