# Generated by Django 5.2.14 on 2026-05-09 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_fields'),
        ('cms', '0002_canteenlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='cms.canteenlocation')),
            ],
            options={
                'db_table': 'cms_menu_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CanteenMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, help_text='Stored in MEDIA_ROOT/menu_items/. Use .url for the full path.', null=True, upload_to='menu_items/')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Default price. Overridden by cms_pricing_rules in Phase 2.', max_digits=10)),
                ('unit', models.CharField(default='plate', max_length=30)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MEAL', 'Meal')], default='MEAL', max_length=20)),
                ('display_tag', models.CharField(blank=True, default='', max_length=50)),
                ('max_qty_per_order', models.PositiveIntegerField(default=3)),
                ('max_qty_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.canteenlocation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cms.menucategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menu_items', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_canteen_menu_items',
                'ordering': ['canteen_id', 'name'],
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['canteen_id', 'is_active'], name='idx_mcat_canteen_active'),
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('canteen', 'name')},
        ),
        migrations.AddIndex(
            model_name='canteenmenuitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'name'], name='idx_mi_canteen_del_name'),
        ),
        migrations.AddIndex(
            model_name='canteenmenuitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'category_id'], name='idx_mi_canteen_del_cat'),
        ),
        migrations.AddIndex(
            model_name='canteenmenuitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'item_type'], name='idx_mi_canteen_del_type'),
        ),
        migrations.AddIndex(
            model_name='canteenmenuitem',
            index=models.Index(fields=['canteen_id', 'deleted_at', 'is_available'], name='idx_mi_canteen_del_avail'),
        ),
        migrations.AddIndex(
            model_name='canteenmenuitem',
            index=models.Index(fields=['id', 'canteen_id', 'deleted_at'], name='idx_mi_id_canteen_del'),
        ),
    ]
