# Generated by Django 5.2.14 on 2026-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_menuitem_guestorder_guestorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('collected', 'Collected'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_column='status', default='pending', max_length=20),
        ),
    ]
