# Generated by Django 5.2.14 on 2026-05-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_mealslot_slotmenuitem'),
        ('cms', '0004_alter_guestorder_status'),
    ]

    operations = [
    ]
