# Generated by Django 5.2.14 on 2026-05-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_merge_menu_and_guest_order_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteenmenuitem',
            name='max_qty_per_day',
        ),
        migrations.RemoveField(
            model_name='canteenmenuitem',
            name='max_qty_per_order',
        ),
        migrations.RemoveField(
            model_name='canteenmenuitem',
            name='unit',
        ),
    ]
