# Generated by Django 5.2.14 on 2026-05-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_merge_20260509_1300'),
        ('cms', '0008_remove_canteenmenuitem_max_qty_per_day_and_more'),
    ]

    operations = [
    ]
