# Generated by Django 5.2.14 on 2026-05-11 09:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_fields'),
        ('cms', '0008_remove_canteenmenuitem_max_qty_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(help_text='e.g. CMS-A4X9Q2. Generated on creation by order service.', max_length=20, unique=True)),
                ('slot_id', models.UUIDField(db_column='slot_id', help_text='The meal slot this order belongs to.')),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_printed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('is_billed', models.BooleanField(db_index=True, default=False, help_text='True after this order is included in a payroll billing summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, db_column='accepted_by', help_text='Admin or Kitchen user who moved order to PREPARING.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='accounts.employee')),
                ('cancelled_by', models.ForeignKey(blank=True, db_column='cancelled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to='accounts.employee')),
                ('canteen', models.ForeignKey(db_column='canteen_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cms.canteenlocation')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_orders',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit — charge for collected order'), ('CREDIT', 'Credit — reversal for cancellation'), ('ADJUSTMENT', 'Adjustment — manual correction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Transaction type determines charge vs reversal.', max_digits=10)),
                ('billing_month', models.CharField(help_text='Format: YYYY-MM  e.g. 2025-01', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='True after billing period is locked. Row must not be modified.')),
                ('transacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('canteen', models.ForeignKey(db_column='canteen_id', on_delete=django.db.models.deletion.PROTECT, related_name='billing_ledger_entries', to='cms.canteenlocation')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', help_text='NULL = system-generated (e.g. auto-billing on DELIVERED).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_entries', to='accounts.employee')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='billing_ledger_entries', to='accounts.employee')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='billing_entries', to='cms.order')),
            ],
            options={
                'db_table': 'cms_billing_ledger',
                'ordering': ['-transacted_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name_snapshot', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(db_column='menu_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='cms.canteenmenuitem')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.order')),
            ],
            options={
                'db_table': 'cms_order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('changed_by_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Admin'), ('KITCHEN', 'Kitchen'), ('COUNTER', 'Counter'), ('SYSTEM', 'System')], max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to='accounts.employee')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cms.order')),
            ],
            options={
                'db_table': 'cms_order_status_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_reversals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_deduction', models.DecimalField(decimal_places=2, default=0, help_text='total_amount - total_reversals. Always recomputed — never set manually.', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — editable, not sent to payroll'), ('FINALISED', 'Finalised — locked, awaiting payroll'), ('PROCESSED', 'Processed — payroll confirmed deduction')], db_index=True, default='DRAFT', max_length=20)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='billing_summaries', to='accounts.company')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='billing_summaries', to='accounts.employee')),
                ('finalised_by', models.ForeignKey(blank=True, db_column='finalised_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalised_billing_summaries', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_billing_summaries',
                'ordering': ['-billing_month', 'employee_id'],
                'indexes': [models.Index(fields=['company_id', 'billing_month', 'status'], name='idx_bs_company_month_status'), models.Index(fields=['billing_month', 'status'], name='idx_bs_month_status')],
                'unique_together': {('employee', 'billing_month')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['employee_id', 'status'], name='idx_ord_employee_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['employee_id', 'order_date'], name='idx_ord_employee_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['canteen_id', 'order_date', 'status'], name='idx_ord_canteen_date_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['canteen_id', 'status', 'placed_at'], name='idx_ord_canteen_status_placed'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['canteen_id', 'is_billed', 'status'], name='idx_ord_canteen_billed_status'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['employee_id', 'billing_month'], name='idx_bl_employee_month'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['canteen_id', 'billing_month'], name='idx_bl_canteen_month'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['billing_month', 'is_locked'], name='idx_bl_month_locked'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['menu_item_id', 'created_at'], name='idx_oi_menuitem_created'),
        ),
    ]
