# Generated by Django 5.2.14 on 2026-05-11 11:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_fields'),
        ('cms', '0009_order_billingledger_orderitem_orderstatuslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_recharged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='canteen_wallet', to='accounts.employee')),
            ],
            options={
                'db_table': 'cms_canteen_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='accounts.employee')),
                ('order', models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='cms.order')),
                ('wallet', models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cms.canteenwallet')),
            ],
            options={
                'db_table': 'cms_wallet_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id', 'created_at'], name='idx_wtxn_employee_created'), models.Index(fields=['order_id'], name='idx_wtxn_order')],
            },
        ),
    ]
