# Generated by Django 5.2.14 on 2026-05-11 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_merge_wallet_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(choices=[('NEW SESSION', 'New Session'), ('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='NEW SESSION', max_length=20)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('MEAL', 'Meal')], db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canteen', models.ForeignKey(db_column='canteen_id', on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='cms.canteenlocation')),
            ],
            options={
                'db_table': 'cms_meal_slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlotMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_item_id', models.UUIDField(help_text="UUID of CanteenMenuItem. No DB FK constraint — validated at app layer to ensure item belongs to slot's canteen.")),
                ('is_enabled', models.BooleanField(default=True, help_text="Admin toggle — False hides this item from the slot's menu.")),
                ('max_qty_per_order', models.PositiveIntegerField(default=3, help_text='Per-order quantity cap for this item in this slot.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.CASCADE, related_name='slot_items', to='cms.mealslot')),
            ],
            options={
                'db_table': 'cms_slot_menu_items',
            },
        ),
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['canteen_id', 'date', 'label'], name='idx_slot_canteen_date_label'),
        ),
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['canteen_id', 'is_active', 'date'], name='idx_slot_canteen_active_date'),
        ),
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['canteen_id', 'date', 'meal_type'], name='idx_slot_canteen_date_mealtype'),
        ),
        migrations.AddConstraint(
            model_name='mealslot',
            constraint=models.UniqueConstraint(fields=('canteen', 'date', 'name'), name='uniq_slot_canteen_date_name'),
        ),
        migrations.AddIndex(
            model_name='slotmenuitem',
            index=models.Index(fields=['slot_id', 'is_enabled'], name='idx_smi_slot_enabled'),
        ),
        migrations.AddIndex(
            model_name='slotmenuitem',
            index=models.Index(fields=['menu_item_id'], name='idx_smi_menuitem'),
        ),
        migrations.AddConstraint(
            model_name='slotmenuitem',
            constraint=models.UniqueConstraint(fields=('slot', 'menu_item_id'), name='uniq_slot_menu_item'),
        ),
    ]
