# Generated by Django 5.2.14 on 2026-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_link_orders_to_mealslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PLACED', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='from_status',
            field=models.CharField(blank=True, choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='to_status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20),
        ),
    ]
