# Generated by Django 5.2.14 on 2026-05-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_add_expired_order_status'),
        ('cms', '0015_slotmenuitem_available_quantity'),
    ]

    operations = [
    ]
