# Generated by Django 4.2.16 on 2026-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_merge_20260513_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmenuitem',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Maximum quantity allowed per order for this dish in this slot.'),
        ),
        migrations.AddField(
            model_name='slotmenuitem',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required per order for this dish in this slot.'),
        ),
        migrations.AddConstraint(
            model_name='slotmenuitem',
            constraint=models.CheckConstraint(check=models.Q(('min_order_quantity__gte', 1)), name='chk_smi_min_order_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='slotmenuitem',
            constraint=models.CheckConstraint(check=models.Q(('max_order_quantity__gte', models.F('min_order_quantity'))), name='chk_smi_max_order_quantity_gte_min'),
        ),
    ]
