# Generated by Django 4.2.16 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_slotmenuitem_max_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenwallet',
            name='monthly_spending_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount employee can spend in a calendar month. Empty means unlimited.', max_digits=10, null=True),
        ),
    ]
