# Generated by Django 4.2.16 on 2026-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_canteenwallet_monthly_spending_limit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mealslot',
            name='idx_slot_canteen_date_label',
        ),
        migrations.RemoveField(
            model_name='mealslot',
            name='label',
        ),
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['canteen_id', 'date'], name='idx_slot_canteen_date'),
        ),
    ]
