# Generated by Django 5.0.14 on 2026-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_mealslot_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealslot',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
