# Generated by Django 5.0.14 on 2026-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_kitchencounteruser_username_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteenmenuitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price visible only to eligible housekeeping employees.', max_digits=10, null=True),
        ),
    ]
