# Generated by Django 5.2.14 on 2026-05-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_canteenmenuitem_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenmenuitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price visible only to eligible employee categories.', max_digits=10, null=True),
        ),
    ]
