# Generated by Django 5.2.14 on 2026-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_order_version_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(help_text='5-digit numeric order code generated on creation by order service.', max_length=20, unique=True),
        ),
    ]
