# Generated by Django 4.2.16 on 2026-05-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_2fa_verified_at',
            field=models.DateTimeField(blank=True, help_text='When user last completed OTP verification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If true, employee must reset password before normal login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='When password was last changed or reset', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='require_otp_after_password_change',
            field=models.BooleanField(default=False, help_text='If true, next login requires OTP after password was changed/reset'),
        ),
    ]
