# Generated by Django 5.0.14 on 2026-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_2fa_auth_state_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('CANTEEN_ADMIN', 'Canteen Admin'), ('LIMITED_ADMIN', 'Limited Admin'), ('HR_MANAGER', 'HR Manager'), ('PAYROLL_MANAGER', 'Payroll Manager'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=50),
        ),
    ]
