# Generated by Django 5.2.14 on 2026-05-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_type'),
        ('cms', '0021_merge_0020_specialdish_0020_mealslot_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='cms.canteenlocation'),
        ),
    ]
