# Generated by Django 5.0.14 on 2026-05-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_canteen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecategory',
            name='is_discount_eligible',
            field=models.BooleanField(default=False, help_text='Mark this employee category as eligible for discounted menu pricing.'),
        ),
    ]
